### ISSUE TITLE
Optimize lookups by considering key sorting

### ISSUE THREAD

**Issue by na--** [mstoykov/atlas#12]
`Node.ValueByKey()` and `Node.Contains()` can probably be improved by taking into account that the keys are sorted. So we don't always need to reach the root - if the key of the current Node is "lower' than the one we are comparing it against, we don't need to dig any deeper, right?

**Comment by Mihai22125** [comment]
Hello @mstoykov, can I work on this?

**Comment by mstoykov** [comment]
Go for it @Mihai22125
